### PR TITLE
Rhmap 9814

### PR DESCRIPTION
**Pull request by pb82**
# Motivation

we want the auth cache interval to be configurable. Since this code is running in a Cloud App the best way to do it is via environment variable. If a variable `AUTH_CACHE_REFRESH_SECONDS` is defined then it will be used to retrieve the cache length. Otherwise we use a default value of 1 hour.

ping @wei-lee @ziccardi @TommyJ1994 @witmicko @aliok

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.
Fhcap PR will be generated automatically.
To deploy your changes to a cluster place comment in this PR with pattern [x][y] where x=deploy and y=clustername you wish to deploy. 
You can also deploy your change manually using fhcap-cli

**Comment by pb82** [comment]
retest this please

**Comment by TommyJ1994** [comment]
LGTM. 

Plato seems to be causing lots of problems in a few components in Node 0.10.
I experienced the same in another component and @wtrocki advised to update the build parameters to only use node 4.4. Might be a similar case here.

**Comment by wei-lee** [comment]
LGTM

**Pull request closed without merging**
